server:
  port: 8880
spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: product-server
        uri: http://localhost:8882/
        predicates:
        - Path=/product/**
      - id: order_server
        uri: http://localhost:8881/
        predicates:
        - Path=/order/**
      - id: auth_server
        uri: http://localhost:8082/
        predicates:
        - Path=/auth-api/**
  main:
    allow-bean-definition-overriding: true

