spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    datasource1:
      url: jdbc:mysql://localhost:3306/datasource1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 20
      min-idle: 1
      initial-size: 1
      test-on-borrow: true
    datasource2:
      url: jdbc:mysql://localhost:3306/datasource2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 20
      min-idle: 1
      initial-size: 1
      test-on-borrow: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
