server:
  port: 8082
  servlet:
    context-path: /auth-api
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security-oauth2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

  redis:
    lettuce:
      pool:
        max-active: 100
        max-idle: 20
        max-wait: 4s
    timeout: 10s
    cluster:
      nodes:
        - 172.16.0.112:6001
        - 172.16.0.112:6002
        - 172.16.0.112:6003

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework:
        security: trace